# Makefile for blastwave_multifile code, Jonathan Mackey
# # Modified version of Makefile.plotradius
#
# 2010.10.13 JM: Updated for new code!
# 2010.12.08 JM: Added cell_interface.o
# 2010.12.09 JM: Modified from Makefile.plotradius

SHELL = /bin/sh
.SUFFIXES:
.SUFFIXES: .cc .o
srcdir = .

# --------------------
# Compile-time options
# --------------------
# Tell it that we're compiling parallel version of code
OPT = -DPARALLEL
# Tell it to use MPI or FILE_COMMS for the inter-process communication.
#IOMODE=USE_FILE_COMMS
IOMODE=USE_MPI
OPT += -D$(IOMODE)

# if using Silo
OPT += -DSILO
# if using FITS
#OPT += -DFITS

MAKE_UNAME=standard
#MAKE_UNAME=epona
#MAKE_UNAME=stokes

# All machines and options need readline and maths
LDFLAGS = -lreadline
# display all warnings
CXXFLAGS = -O3 
#CXXFLAGS += -Wall

######################################################################
# Options for a "standard" workstation.
# make sure cfitsio and silo are compiled in ../extra_libraries/
######################################################################
ifeq ($(MAKE_UNAME), standard)
ifeq ($(IOMODE), USE_FILE_COMMS)
CXX = g++
endif
ifeq ($(IOMODE), USE_MPI)
CXX = mpicxx
endif
#CXXFLAGS = -O3
#CXXFLAGS = -O3 -g
CXXFLAGS = -O0 -Wall -g

MYLIB = ../../extra_libraries

# Includes for FITS/SILO
INC = -I${MYLIB}/fits_lib/include
# for Silo, without HDF5 here
INC += -I${MYLIB}/silo_lib/include

LDFLAGS =  -lm  -lreadline

## If we want static linking this is the flag for it!
#LDFLAGS += -static
# Libraries for fits, silo
LDFLAGS += -L${MYLIB}/fits_lib/lib -lcfitsio
LDFLAGS += -L${MYLIB}/silo_lib/lib -lsilo 
endif

###################################################
# Specific Options for epona (ubuntu 9.10 32-bit) #
###################################################
ifeq ($(MAKE_UNAME), epona)
ifeq ($(IOMODE), USE_FILE_COMMS)
CXX = g++
endif
ifeq ($(IOMODE), USE_MPI)
CXX = mpicxx
endif

#CXXFLAGS = -O3
#CXXFLAGS = -O2
CXXFLAGS = -Wall -g

MYLIB = /mnt/local/jm/local_libs

# Includes for FITS/SILO
INC = -I$(MYLIB)/cfitsio_gcc/include
# for Silo, which may or may not use HDF5... (comment as appropriate)
INC += -I/usr/include -fomit-frame-pointer
#INC += -I$(MYLIB)/silo_gcc_nohdf/include
INC += -I$(MYLIB)/silo_gcc_hdf5/include
#INC += -I$(MYLIB)/silo_visittest/include

LDFLAGS =  -lm  -lreadline
# Libraries for fits, silo (with hdf5)
LDFLAGS += -L$(MYLIB)/cfitsio_gcc/lib/ -lcfitsio
#LDFLAGS += -L$(MYLIB)/silo_gcc_nohdf/lib/ -lsilo
LDFLAGS += -L$(MYLIB)/silo_gcc_hdf5/lib/ -lsiloh5
#LDFLAGS += -L$(MYLIB)/silo_visittest/lib/ -lsiloh5
LDFLAGS += -L/usr/lib/ -lhdf5 -lhdf5_cpp
LDFLAGS += -lz -lpthread
endif
#################################################


##################################################
##################################################

CXXFLAGS += $(OPT)
VPATH = ../../source

OBJECTS = blastwave_multifile.o uniformGrid.o readparams.o global.o \
	dataio_silo.o dataio_utility.o dataio.o dataio_silo_MPI.o \
	VectorOps.o VectorOps_spherical.o \
	stellar_wind_BC.o cell_interface.o \
	comm_mpi.o comm_files.o 

BW_multifile: $(OBJECTS)
	$(CXX) $(CXXFLAGS) $(INC) $(OBJECTS) -o BW_multifile $(LDFLAGS)

# make has rules for making objects from .cc files, so I don't need them
# explicitly, unless I am doing something unusual.
.cc.o:
	$(CXX) $(CXXFLAGS) $(INC) -c $<

blastwave_multifile.o:	blastwave_multifile.cc global.h uniformGrid.h \
			dataio.h dataio_silo.h dataio_utility.h \
			VectorOps.h VectorOps_spherical.h
global.o: 	global.cc global.h
uniformGrid.o: 	uniformGrid.cc uniformGrid.h global.h stellar_wind_BC.h \
		VectorOps.h VectorOps_spherical.h
dataio.o:       dataio.cc dataio.h global.h solver_eqn_base.h readparams.h
dataio_silo.o:  dataio_silo.cc dataio_silo.h dataio.h global.h solver_eqn_base.h
#dataio_fits.o:  dataio_fits.cc dataio_fits.h dataio.h global.h solver_eqn_base.h solver_eqn_hydro_adi.h solver_eqn_hydro_iso.h
readparams.o:   readparams.cc readparams.h global.h
#utility_fits_class.o: utility_fits_class.cc dataio_fits.h dataio.h global.h

dataio_utility: dataio_utility.cc dataio_utility.h dataio_silo.h \
		dataio_silo_MPI.h dataio.h global.h sub_domain_comms.h file_status.h

dataio_silo_MPI.o:    dataio_silo_MPI.cc dataio_silo.h dataio.h \
		      global.h sub_domain_comms.h file_status.h

stellar_wind_BC.o: stellar_wind_BC.cc stellar_wind_BC.h global.h
VectorOps.o:           VectorOps.cc VectorOps.h global.h uniformGrid.h
VectorOps_spherical.o: VectorOps_spherical.cc VectorOps_spherical.h VectorOps.h \
		       global.h uniformGrid.h

comm_mpi.o: comm_mpi.cc comm_mpi.h sub_domain_comms.h global.h
comm_files.o: comm_files.cc comm_files.h sub_domain_comms.h global.h

clean:
	rm -f *.o BW_multifile

